version: '3.8'

services:
  web:
    build: .
    container_name: flask-cicd-app
    ports:
      - "5000:5000"
    env_file:
      - .env
    volumes:
      - .:/app
    environment:
      - PYTHONPATH=/app
