name: CI Pipeline

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Create .env file from GitHub secrets
      run: echo "SECRET_KEY=${{ secrets.SECRET_KEY }}" > .env

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Build Docker image
      run: docker compose build
      
    - name: Run tests in container
      run: docker compose run --rm web sh -c "pytest"

